
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      #change it to .env later
      POSTGRES_USER: msumon
      POSTGRES_PASSWORD: msumon1234
      POSTGRES_DB: pongdb
    ports:
      - "5432:5432"

  django: 
    build: ./backend
    container_name: django
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  nginx:
      image: nginx:latest
      container_name: nginx
      ports:
        - "443:443"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/certs:/etc/nginx/certs
      depends_on:
        - django
