
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: msumon
      POSTGRES_PASSWORD: msumon1234
      POSTGRES_DB: pongdb
    ports:
      - "5432:5432"

  django: 
    build: ./backend
    container_name: django
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=pong.settings

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"