
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      #change it to .env later
      POSTGRES_USER: msumon
      POSTGRES_PASSWORD: msumon1234
      POSTGRES_DB: pongdb
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  django: 
    build: ./backend
    container_name: django
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  postgres_data:
  