
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - ./backend/.env
    # environment:
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  django: 
    build: ./backend
    container_name: django
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=pong.settings

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6380"
