
services:
  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - postgres


  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      #change it to .env later
      POSTGRES_USER: msumon
      POSTGRES_PASSWORD: msumon1234
      POSTGRES_DB: pongdb

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
