FROM python:3.11

WORKDIR /app/pong

COPY requirements.txt .
RUN pip install -r requirements.txt

RUN apt-get update && apt-get install -y postgresql-client

COPY . .

COPY django-setup.sh /tmp/django-setup.sh

RUN chmod +x /tmp/django-setup.sh

ENTRYPOINT [ "/tmp/django-setup.sh" ]