# Generated by Django 3.2.25 on 2024-12-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20241201_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerscore',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
