# Generated by Django 3.2.25 on 2024-12-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_playerscore_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerTotalScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100, unique=True)),
                ('total_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='playerscore',
            name='total_score',
        ),
        migrations.AlterField(
            model_name='playerscore',
            name='player_name',
            field=models.CharField(max_length=100),
        ),
    ]
