# Generated by Django 3.2.25 on 2024-12-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20241204_1226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerTotalScore',
        ),
        migrations.RemoveField(
            model_name='playerscore',
            name='result',
        ),
        migrations.AlterField(
            model_name='playerscore',
            name='player_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
