# Generated by Django 3.2.25 on 2024-12-04 14:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_playerscore_total_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerscore',
            name='date',
        ),
        migrations.RemoveField(
            model_name='playerscore',
            name='score',
        ),
        migrations.AddField(
            model_name='playerscore',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='playerscore',
            name='scores',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='playerscore',
            name='player_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
