# Generated by Django 5.1.4 on 2024-12-20 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_friendship_delete_block'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendship',
            options={'verbose_name': 'Friendship', 'verbose_name_plural': 'Friendships'},
        ),
    ]
