# Generated by Django 5.1.4 on 2024-12-20 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_friendship_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendship',
            options={},
        ),
    ]
