# Generated by Django 5.1.4 on 2024-12-22 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
