name: Deploy Django Static Files and Templates to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.17.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # Build and start the container
      - name: Build and start the container
        run: |
          docker-compose up --build -d

      # Collect static files from Django app
      - name: Collect static files
        run: |
          docker-compose exec django python manage.py collectstatic --noinput

      # Copy templates (such as index.html) to the deploy directory
      - name: Copy templates directory
        run: |
          cp -r ./backend/pong/users/templates ./deploy_directory

      # Upload static files and templates as artifacts
      - name: Upload static files and templates as artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: |
            ./static
            ./deploy_directory/templates

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          path: ./static
